[project]
name = "bayes"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "Julien Malard-Adam", email = "julien.malard@mail.mcgill.ca" },
]
dependencies = [
    "arviz>=1.1.0",
    "ennikkai>=1.2.6",
    "graphviz>=0.21",
    "matplotlib>=3.10.9",
    "pgmpy>=1.1.2",
    "pymc>=6.0.0",
    "pymc-extras>=0.11.0",
]
requires-python = "<3.13.0,>=3.12"
readme = "README.md"
license = { text = "AGPL-3.0" }


[tool.pdm]
distribution = false
